// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
)

type History struct {
	HistoryID int32  `json:"history_id"`
	UrlID     int32  `json:"url_id"`
	AccessDt  string `json:"access_dt"`
}

type Statistic struct {
	UrlID           int32 `json:"url_id"`
	TwentyFourHours int32 `json:"twenty_four_hours"`
	LastSevenDays   int32 `json:"last_seven_days"`
	AllTime         int32 `json:"all_time"`
}

type Url struct {
	UrlID        int32         `json:"url_id"`
	LongUrl      string        `json:"long_url"`
	ShortUrl     string        `json:"short_url"`
	ExpirationDt sql.NullInt32 `json:"expiration_dt"`
}
