// Code generated by sqlc. DO NOT EDIT.
// source: STATISTIC_QUERIES.sql

package datastore

import (
	"context"
)

const getStatisticsByUrl = `-- name: GetStatisticsByUrl :one
SELECT url_id, twenty_four_hours, last_seven_days, all_time FROM STATISTICS WHERE url_id = $1
`

func (q *Queries) GetStatisticsByUrl(ctx context.Context, urlID int32) (Statistic, error) {
	row := q.db.QueryRowContext(ctx, getStatisticsByUrl, urlID)
	var i Statistic
	err := row.Scan(
		&i.UrlID,
		&i.TwentyFourHours,
		&i.LastSevenDays,
		&i.AllTime,
	)
	return i, err
}
